[package]
name = "NymX-Mail"
version = "0.1.0"
edition = "2021"
authors = ["Ch1ffr3punk"]
description = "NymX Mail - Anonymous emails leveraging SURBs via the Nym Mixnet"
license = "Apache 2.0"

[dependencies]
nym-sdk = "1.21.2"
tokio = { version = "1", features = ["full"] }
rand = "0.8"
ripemd = "0.1"
hex = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ssh2 = "0.9"
eframe = "0.28"
rfd = "0.14"
open = "5.0"
image = "0.25"
filetime = "0.2"
filetime_creation = "0.2"

[build-dependencies]
winres = "0.1"


